config/routes.rb
Rails.application.routes.draw do

  # get 'users/show'
  # get 'users/edit'
  # get 'users/destroy'
  devise_for :users
  root to: "pages#home"
  # Users routes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books do
    resources :reviews, only: %i[index new create]
    resources :bookings, only: %i[index new create]
  end

  resources :reviews, only: %i[show destroy]
  resources :bookings, only: %i[show destroy]

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews

  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model

  pg_search_scope :search_by_title_and_category,
    against: [ :title, :book_category, :language],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :bookings
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name birth_date])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name birth_date])
  end

  private
  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_params, only: %i[show destroy]
  before_action :set_book, only: %i[new create]

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    authorize @booking
  end

  def new
    @booking = Booking.new
    authorize @booking # Add this line
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.book = @book
    authorize @booking
    if @booking.save!
      redirect_to book_path(Book.find(params[:book_id])), status: :see_other, notice: "Your booking has been added!!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @booking
    book_id = @booking.book_id
    @booking.destroy
    redirect_to book_bookings_path(book_id), status: :see_other, notice: "Your booking has been deleted!!"
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end

  def set_params
    @booking = Booking.find(params[:id])
  end

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_params, only: %i[show edit update destroy]

  def index
    @books = policy_scope(Book)
      if params[:query].present?
        @books = Book.search_by_title_and_category(params[:query])
      else
        @books = Book.all
      end
    @markers = @books.geocoded.map do |book|
      {
        lat: book.latitude,
        lng: book.longitude
      }
    end
  end


  def show
    @reviews = Review.where(book_id: @book)
    authorize @book
    # Add this line
  end

  def new
    @book = Book.new
    authorize @book # Add this line
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    authorize @book
    if @book.save!
      redirect_to book_path(@book), notice: "Your book has been added!!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @book
  end

  def update
    authorize @book
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "Your book has been edited!!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @book
    @book.destroy
    redirect_to books_path, notice: "Your book has been deleted!!"
  end

  private

  def book_params
    params.require(:book).permit(:title, :book_category, :language, :photo)
  end

  def set_params
    @book = Book.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @books1 = Book.where(user_id: current_user)
    @books2 = Book.where.not(user_id: current_user).first(3)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 before_action :set_params, only: %i[show destroy]
  before_action :set_book, only: %i[new create]

  def index
    @reviews = policy_scope(Review)
  end

  def show
    authorize @review
  end

  def new
    @review = Review.new
    authorize @review # Add this line
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.book = @book
    authorize @review
    if @review.save!
      redirect_to book_path(@book), status: :see_other, notice: "Your review has been added!!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @review
    book_id = @review.book_id
    @review.destroy
    redirect_to book_path(Book.find(params[:book_id])), status: :see_other, notice: "Your review has been deleted!!"
  end

  private

  def review_params
    params.require(:review).permit(:content, :anonimously)
  end

  def set_params
    @review = Review.find(params[:id])
  end

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def show
  end

  def edit
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Here are all the bookings</h1>

<% @bookings.each do |booking| %>
  <h4><%= link_to booking.start_time, booking_path(booking) %></h4>
<% end %>

<%= cl_image_tag("mpyg2072i73iwhieclto", width: 400, height: 300, crop: :fill) %>

app/views/bookings/new.html.erb
<h1 class="mx-5 mt-3">Create your booking</h1>

<div class="mx-5 d-flex flex-column">
  <%= simple_form_for [@book, @booking] do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :start_time, :order => [:month, :day], input_html: { autocomplete: "Starting Date" } %>
      <%= f.input :end_time, :order => [:month, :day], input_html: { autocomplete: "Ending Date" } %>
    </div>
    <div class="form-actions d-flex" style="color: white;">
      <button class="btn btn-primary p-1"><%= f.button :submit, "Create booking" %></button>
      <%= link_to "Home", books_path, {:style=>'color:black; text-decoration: none;',
      :class=>"btn btn-primary mx-3 d-flex align-items-center justify-content-center"} %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1>Here are your booking details!</h1>

<h2>Start time:</h2>
<h4><%= @booking.start_time %></h4>

<h2>End time:</h2>
<h4><%= @booking.end_time %></h4>

<%= link_to "Delete",
  booking_path(@booking),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/books/edit.html.erb
<h1>Edit the book</h1>
<%= simple_form_for [@book] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title,
                required: true,
                autofocus: true,
                input_html: { autocomplete: @book.title } %>
  <%= f.input :book_category,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: @book.book_category } %>
  <%= f.input :language,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: @book.language } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Edit" class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/books/index.html.erb
<div class="search-bar-container my-3">
  <%= form_with url: books_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a book"
    %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
</div>

<div class="text-center font-weight-bold border">
   <h1 class="hello" style="line-height: 2em;">All Books👇</h1>
</div>

<div class="index-container mr-3">
  <div class="books-grid mx-4">
    <% @books.each do |book| %>
      <%= render partial: "shared/card", locals: {book: book }  %>
    <%end%>
  </div>
  <div class="map-container mt-2 pr-3" data-controller="map"
       data-map-markers-value="<%= @markers.to_json %>"
       data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/books/new.html.erb
<h1>Create your book</h1>
<%= simple_form_for [@book] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs m-4">
    <%= f.input :title,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "title" } %>
  <%= f.input :book_category,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "book_category" } %>
  <%= f.input :language,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "language" } %>

  <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions m-4  ">

 <button class="btn btn-primary"><%= f.button :submit, "Create" %></button>
  </div>
<%= link_to "Home", books_path %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <h1 style="line-height: 2em;">Books details</h1>

  <div>
    <div class="book-card1 d-flex justify-content-left">
      <div class="book-image my-3 mx-3">
        <%= cl_image_tag @book.photo.key, height: 400, width: 300, crop: :fill, style: "border-radius: 15px" %>
      </div>

      <div class="d-flex row">
        <div class="book-details my-3 mx-3">
          <h4>Title</h4>
          <h4><%= @book.title %></h4>
          <h5>Book category:</h5>
          <%= @book.book_category %>
        </div>

        <div class="mx-3">
          <%= link_to "Rent this book", new_book_booking_path(@book), class: "btn btn-success"%>
          <%= link_to "Add a review", new_book_review_path(@book), class: "btn btn-success"%>
        </div>
      </div>

    </div>
  </div>
</div>







<div class="reviews-container border border-top-0 mt-4 bg-white rounded p-3 shadow">
  <div class="bg-white rounded p-3 shadow border border-5 ">
    <h3>Reviews</h3>
    <% if @reviews.length == 0 %>
      <hr>
      <h5 style="color: red"> There are not reviews yet !!</h5>
    <% end %>
    <hr>
    <% @reviews.order(created_at: :desc).each do |review| %>
      <p style="font-size: 20px; font-weight: light;"><%= review.content %></p>
      <% if review.user_id == current_user.id%>
        <div class="btn btn-danger ">
          <%= link_to "Delete", review_path(review),{:style=>'color:white; text-decoration: none;'}%>
        </div>
      <% end %>
        <hr>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
  </body>

</html>

app/views/pages/home.html.erb
<div class="banner my-3">
  <div class="text-center" data-aos="zoom-out-up"><div>
  <h1 style="line-height: 2em;" class="my-3 mx-3 font-weight-bold border"> Welcome <%= current_user.first_name %></h1>
</div>


<div data-aos="fade-up"
  data-aos-easing="linear"
  data-aos-duration="1500">
  <div class="row">
    <div class="books-grid d-flex justify-content-around">
      <% @books1.each do |book| %>
        <%= render partial: "shared/card", locals: {book: book }  %>
      <%end%>
    </div>
  </div>
</div>

<div class="my3">
  <div data-aos="zoom-in-right">
    <h2 class="my-3 mx-3 font-weight-bold border" style="line-height: 3em;">Your rented books</h2>
  </div>
</div>

</div>
  <div data-aos="fade-up"
    data-aos-easing="linear"
    data-aos-duration="1500">
    <div class="row">
      <div class="books-grid d-flex justify-content-around">
        <% @books2.each do |book| %>
          <%= render partial: "shared/card", locals: {book: book }  %>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>This are the available books</h1>

<h1></h1>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<% @reviews.each do |review| %>
  <h4><%= link_to review.content, review_path(review) %></h4>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create your review here</h1>
        <%= simple_form_for [@book, @review] do |f| %>
          <%= f.error_notification %>
          <%= f.input :content%>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="form-actions d-flex" style="color: white;""></div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Here are your reviews!</h1>


<h2>Reviews:</h2>
<h4><%= @review.content %></h4>

<%= link_to "Delete",
  review_path(@review),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<!-- do @reviews.reverse.each in if statment -->

app/views/shared/_card.html.erb
            <div class="book-card">
              <div class="book-card-info w-100 h-100 pt-3 d-flex flex-column">
                  <% if book.photo.attached? %>
                    <%= cl_image_tag book.photo.key, crop: :fill %>
                  <% else %>
                    <%= book.title %>
                  <% end %>

                <div class="h-100 d-flex align-items-center my-auto justify-content-center">
                  <p class="text-center m-0 py-3">
                  <%= link_to "Read more", book_path(book), {:style=>'color:black; text-decoration: none;'}%>
                  </p>
                </div>
              </div>
            </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://us.123rf.com/450wm/sergeypykhonin/sergeypykhonin1809/sergeypykhonin180900041/108230283-registration-register-logo-or-label-diary-note-icon-vector-illustration.jpg?ver=6" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item"></li>
            <%= link_to "My Books", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://us.123rf.com/450wm/sergeypykhonin/sergeypykhonin1809/sergeypykhonin180900041/108230283-registration-register-logo-or-label-diary-note-icon-vector-illustration.jpg?ver=6", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create a book", new_book_path, class: "dropdown-item" %>
              <%= link_to "Add a review", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>